package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.CartItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CART_ITEM.
*/
public class CartItemDao extends AbstractDao<CartItem, Long> {

    public static final String TABLENAME = "CART_ITEM";

    /**
     * Properties of entity CartItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Item_id = new Property(0, Long.class, "item_id", true, "ITEM_ID");
        public final static Property Product_id = new Property(1, Long.class, "product_id", false, "PRODUCT_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Sku = new Property(3, String.class, "sku", false, "SKU");
        public final static Property Manufacturer = new Property(4, String.class, "manufacturer", false, "MANUFACTURER");
        public final static Property Price = new Property(5, Float.class, "price", false, "PRICE");
        public final static Property Image_url = new Property(6, String.class, "image_url", false, "IMAGE_URL");
        public final static Property Qty = new Property(7, Integer.class, "qty", false, "QTY");
        public final static Property Row_total = new Property(8, Float.class, "row_total", false, "ROW_TOTAL");
        public final static Property Options = new Property(9, String.class, "options", false, "OPTIONS");
        public final static Property Discount_amount = new Property(10, Float.class, "discount_amount", false, "DISCOUNT_AMOUNT");
        public final static Property Tax_amount = new Property(11, Float.class, "tax_amount", false, "TAX_AMOUNT");
        public final static Property Type_id = new Property(12, String.class, "type_id", false, "TYPE_ID");
    };


    public CartItemDao(DaoConfig config) {
        super(config);
    }
    
    public CartItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CART_ITEM' (" + //
                "'ITEM_ID' INTEGER PRIMARY KEY ," + // 0: item_id
                "'PRODUCT_ID' INTEGER," + // 1: product_id
                "'NAME' TEXT," + // 2: name
                "'SKU' TEXT," + // 3: sku
                "'MANUFACTURER' TEXT," + // 4: manufacturer
                "'PRICE' REAL," + // 5: price
                "'IMAGE_URL' TEXT," + // 6: image_url
                "'QTY' INTEGER," + // 7: qty
                "'ROW_TOTAL' REAL," + // 8: row_total
                "'OPTIONS' TEXT," + // 9: options
                "'DISCOUNT_AMOUNT' REAL," + // 10: discount_amount
                "'TAX_AMOUNT' REAL," + // 11: tax_amount
                "'TYPE_ID' TEXT);"); // 12: type_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CART_ITEM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CartItem entity) {
        stmt.clearBindings();
 
        Long item_id = entity.getItem_id();
        if (item_id != null) {
            stmt.bindLong(1, item_id);
        }
 
        Long product_id = entity.getProduct_id();
        if (product_id != null) {
            stmt.bindLong(2, product_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sku = entity.getSku();
        if (sku != null) {
            stmt.bindString(4, sku);
        }
 
        String manufacturer = entity.getManufacturer();
        if (manufacturer != null) {
            stmt.bindString(5, manufacturer);
        }
 
        Float price = entity.getPrice();
        if (price != null) {
            stmt.bindDouble(6, price);
        }
 
        String image_url = entity.getImage_url();
        if (image_url != null) {
            stmt.bindString(7, image_url);
        }
 
        Integer qty = entity.getQty();
        if (qty != null) {
            stmt.bindLong(8, qty);
        }
 
        Float row_total = entity.getRow_total();
        if (row_total != null) {
            stmt.bindDouble(9, row_total);
        }
 
        String options = entity.getOptions();
        if (options != null) {
            stmt.bindString(10, options);
        }
 
        Float discount_amount = entity.getDiscount_amount();
        if (discount_amount != null) {
            stmt.bindDouble(11, discount_amount);
        }
 
        Float tax_amount = entity.getTax_amount();
        if (tax_amount != null) {
            stmt.bindDouble(12, tax_amount);
        }
 
        String type_id = entity.getType_id();
        if (type_id != null) {
            stmt.bindString(13, type_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CartItem readEntity(Cursor cursor, int offset) {
        CartItem entity = new CartItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // item_id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // product_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sku
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // manufacturer
            cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5), // price
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // image_url
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // qty
            cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8), // row_total
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // options
            cursor.isNull(offset + 10) ? null : cursor.getFloat(offset + 10), // discount_amount
            cursor.isNull(offset + 11) ? null : cursor.getFloat(offset + 11), // tax_amount
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // type_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CartItem entity, int offset) {
        entity.setItem_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProduct_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSku(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setManufacturer(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPrice(cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5));
        entity.setImage_url(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setQty(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setRow_total(cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8));
        entity.setOptions(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDiscount_amount(cursor.isNull(offset + 10) ? null : cursor.getFloat(offset + 10));
        entity.setTax_amount(cursor.isNull(offset + 11) ? null : cursor.getFloat(offset + 11));
        entity.setType_id(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CartItem entity, long rowId) {
        entity.setItem_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CartItem entity) {
        if(entity != null) {
            return entity.getItem_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
