package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CART_DETAIL.
 */
public class CartDetail {

    private Long entity_id;
    private Integer items_count;
    private Integer items_qty;
    private Float subtotal;
    private Float grand_total;
    private String coupon_code;
    private Long customer_id;
    private String created_at;
    private String updated_at;
    private Float tax_amount;
    private Float shipping_amount;
    private Float discount_amount;
    private Float use_reward_points;
    private String discount_description;
    private String voucher_list;

    public CartDetail() {
    }

    public CartDetail(Long entity_id) {
        this.entity_id = entity_id;
    }

    public CartDetail(Long entity_id, Integer items_count, Integer items_qty, Float subtotal, Float grand_total, String coupon_code, Long customer_id, String created_at, String updated_at, Float tax_amount, Float shipping_amount, Float discount_amount, Float use_reward_points, String discount_description, String voucher_list) {
        this.entity_id = entity_id;
        this.items_count = items_count;
        this.items_qty = items_qty;
        this.subtotal = subtotal;
        this.grand_total = grand_total;
        this.coupon_code = coupon_code;
        this.customer_id = customer_id;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.tax_amount = tax_amount;
        this.shipping_amount = shipping_amount;
        this.discount_amount = discount_amount;
        this.use_reward_points = use_reward_points;
        this.discount_description = discount_description;
        this.voucher_list = voucher_list;
    }

    public Long getEntity_id() {
        return entity_id;
    }

    public void setEntity_id(Long entity_id) {
        this.entity_id = entity_id;
    }

    public Integer getItems_count() {
        return items_count;
    }

    public void setItems_count(Integer items_count) {
        this.items_count = items_count;
    }

    public Integer getItems_qty() {
        return items_qty;
    }

    public void setItems_qty(Integer items_qty) {
        this.items_qty = items_qty;
    }

    public Float getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }

    public Float getGrand_total() {
        return grand_total;
    }

    public void setGrand_total(Float grand_total) {
        this.grand_total = grand_total;
    }

    public String getCoupon_code() {
        return coupon_code;
    }

    public void setCoupon_code(String coupon_code) {
        this.coupon_code = coupon_code;
    }

    public Long getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public Float getTax_amount() {
        return tax_amount;
    }

    public void setTax_amount(Float tax_amount) {
        this.tax_amount = tax_amount;
    }

    public Float getShipping_amount() {
        return shipping_amount;
    }

    public void setShipping_amount(Float shipping_amount) {
        this.shipping_amount = shipping_amount;
    }

    public Float getDiscount_amount() {
        return discount_amount;
    }

    public void setDiscount_amount(Float discount_amount) {
        this.discount_amount = discount_amount;
    }

    public Float getUse_reward_points() {
        return use_reward_points;
    }

    public void setUse_reward_points(Float use_reward_points) {
        this.use_reward_points = use_reward_points;
    }

    public String getDiscount_description() {
        return discount_description;
    }

    public void setDiscount_description(String discount_description) {
        this.discount_description = discount_description;
    }

    public String getVoucher_list() {
        return voucher_list;
    }

    public void setVoucher_list(String voucher_list) {
        this.voucher_list = voucher_list;
    }

}
