package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CART_ITEM.
 */
public class CartItem {

    private Long item_id;
    private Long product_id;
    private String name;
    private String sku;
    private String manufacturer;
    private Float price;
    private String image_url;
    private Integer qty;
    private Float row_total;
    private String options;
    private Float discount_amount;
    private Float tax_amount;
    private String type_id;

    public CartItem() {

    }

    public CartItem(Long item_id) {
        this.item_id = item_id;
    }

    public CartItem(Long item_id, Long product_id, String name, String sku, String manufacturer, Float price, String image_url, Integer qty, Float row_total, String options, Float discount_amount, Float tax_amount, String type_id) {
        this.item_id = item_id;
        this.product_id = product_id;
        this.name = name;
        this.sku = sku;
        this.manufacturer = manufacturer;
        this.price = price;
        this.image_url = image_url;
        this.qty = qty;
        this.row_total = row_total;
        this.options = options;
        this.discount_amount = discount_amount;
        this.tax_amount = tax_amount;
        this.type_id = type_id;
    }

    public Long getItem_id() {
        return item_id;
    }

    public void setItem_id(Long item_id) {
        this.item_id = item_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public Integer getQty() {
        return qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public Float getRow_total() {
        return row_total;
    }

    public void setRow_total(Float row_total) {
        this.row_total = row_total;
    }

    public String getOptions() {
        return options;
    }

    public void setOptions(String options) {
        this.options = options;
    }

    public Float getDiscount_amount() {
        return discount_amount;
    }

    public void setDiscount_amount(Float discount_amount) {
        this.discount_amount = discount_amount;
    }

    public Float getTax_amount() {
        return tax_amount;
    }

    public void setTax_amount(Float tax_amount) {
        this.tax_amount = tax_amount;
    }

    public String getType_id() {
        return type_id;
    }

    public void setType_id(String type_id) {
        this.type_id = type_id;
    }

}
