package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

    private Long entity_id;
    private String name;
    private Integer position;
    private String image_url;
    private String thumbnail_url;
    private Integer product_count;

    public Category() {
    }

    public Category(Long entity_id) {
        this.entity_id = entity_id;
    }

    public Category(Long entity_id, String name, Integer position, String image_url, String thumbnail_url, Integer product_count) {
        this.entity_id = entity_id;
        this.name = name;
        this.position = position;
        this.image_url = image_url;
        this.thumbnail_url = thumbnail_url;
        this.product_count = product_count;
    }

    public Long getEntity_id() {
        return entity_id;
    }

    public void setEntity_id(Long entity_id) {
        this.entity_id = entity_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getThumbnail_url() {
        return thumbnail_url;
    }

    public void setThumbnail_url(String thumbnail_url) {
        this.thumbnail_url = thumbnail_url;
    }

    public Integer getProduct_count() {
        return product_count;
    }

    public void setProduct_count(Integer product_count) {
        this.product_count = product_count;
    }

}
