package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.ConfigOption;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CONFIG_OPTION.
*/
public class ConfigOptionDao extends AbstractDao<ConfigOption, Long> {

    public static final String TABLENAME = "CONFIG_OPTION";

    /**
     * Properties of entity ConfigOption.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Option_id = new Property(0, Long.class, "option_id", true, "OPTION_ID");
        public final static Property Label = new Property(1, String.class, "label", false, "LABEL");
        public final static Property Price = new Property(2, Float.class, "price", false, "PRICE");
        public final static Property Position = new Property(3, Integer.class, "position", false, "POSITION");
    };


    public ConfigOptionDao(DaoConfig config) {
        super(config);
    }
    
    public ConfigOptionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CONFIG_OPTION' (" + //
                "'OPTION_ID' INTEGER PRIMARY KEY ," + // 0: option_id
                "'LABEL' TEXT," + // 1: label
                "'PRICE' REAL," + // 2: price
                "'POSITION' INTEGER);"); // 3: position
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CONFIG_OPTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ConfigOption entity) {
        stmt.clearBindings();
 
        Long option_id = entity.getOption_id();
        if (option_id != null) {
            stmt.bindLong(1, option_id);
        }
 
        String label = entity.getLabel();
        if (label != null) {
            stmt.bindString(2, label);
        }
 
        Float price = entity.getPrice();
        if (price != null) {
            stmt.bindDouble(3, price);
        }
 
        Integer position = entity.getPosition();
        if (position != null) {
            stmt.bindLong(4, position);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ConfigOption readEntity(Cursor cursor, int offset) {
        ConfigOption entity = new ConfigOption( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // option_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // label
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // price
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // position
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ConfigOption entity, int offset) {
        entity.setOption_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLabel(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrice(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setPosition(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ConfigOption entity, long rowId) {
        entity.setOption_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ConfigOption entity) {
        if(entity != null) {
            return entity.getOption_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
