package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIG_OPTION.
 */
public class ConfigOption {

    private Long option_id;
    private String label;
    private Float price;
    private Integer position;

    public ConfigOption() {
    }

    public ConfigOption(Long option_id) {
        this.option_id = option_id;
    }

    public ConfigOption(Long option_id, String label, Float price, Integer position) {
        this.option_id = option_id;
        this.label = label;
        this.price = price;
        this.position = position;
    }

    public Long getOption_id() {
        return option_id;
    }

    public void setOption_id(Long option_id) {
        this.option_id = option_id;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
