package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIG_MERGE.
 */
public class ConfigMerge {

    private Long id;
    private Long attribute_id;
    private Long option_id;
    private Long product_id;
    private Integer is_chosen_att;
    private Integer is_chosen_opt;
    private Integer position;

    public ConfigMerge() {
    }

    public ConfigMerge(Long id) {
        this.id = id;
    }

    public ConfigMerge(Long id, Long attribute_id, Long option_id, Long product_id, Integer is_chosen_att, Integer is_chosen_opt, Integer position) {
        this.id = id;
        this.attribute_id = attribute_id;
        this.option_id = option_id;
        this.product_id = product_id;
        this.is_chosen_att = is_chosen_att;
        this.is_chosen_opt = is_chosen_opt;
        this.position = position;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAttribute_id() {
        return attribute_id;
    }

    public void setAttribute_id(Long attribute_id) {
        this.attribute_id = attribute_id;
    }

    public Long getOption_id() {
        return option_id;
    }

    public void setOption_id(Long option_id) {
        this.option_id = option_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public Integer getIs_chosen_att() {
        return is_chosen_att;
    }

    public void setIs_chosen_att(Integer is_chosen_att) {
        this.is_chosen_att = is_chosen_att;
    }

    public Integer getIs_chosen_opt() {
        return is_chosen_opt;
    }

    public void setIs_chosen_opt(Integer is_chosen_opt) {
        this.is_chosen_opt = is_chosen_opt;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
