package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIG_ATTRIBUTE.
 */
public class ConfigAttribute {

    private Long attribute_id;
    private String code;
    private String label;
    private Integer position;

    public ConfigAttribute() {
    }

    public ConfigAttribute(Long attribute_id) {
        this.attribute_id = attribute_id;
    }

    public ConfigAttribute(Long attribute_id, String code, String label, Integer position) {
        this.attribute_id = attribute_id;
        this.code = code;
        this.label = label;
        this.position = position;
    }

    public Long getAttribute_id() {
        return attribute_id;
    }

    public void setAttribute_id(Long attribute_id) {
        this.attribute_id = attribute_id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
