package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COUNTRY.
 */
public class Country {

    private String value;
    private String label;
    private Integer set_default;

    public Country() {
    }

    public Country(String value) {
        this.value = value;
    }

    public Country(String value, String label, Integer set_default) {
        this.value = value;
        this.label = label;
        this.set_default = set_default;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Integer getSet_default() {
        return set_default;
    }

    public void setSet_default(Integer set_default) {
        this.set_default = set_default;
    }

}
