package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOMER.
 */
public class Customer {

    private Long entity_id;
    private String firstname;
    private String middlename;
    private String lastname;
    private String email;
    private String dob;
    private String facebook_id;
    private Boolean is_login_fb;
    private String picture_url;
    private Integer cart_items_count;
    private Integer wishlist_items_count;
    private Integer unread_alerts_count;
    private String shipping_address;
    private String billing_address;
    private Integer is_notification_sound;
    private Integer orders_count;
    private Integer reward_points;
    private Double evoucher_amount;
    private Integer log_num;
    private String card_code;

    public Customer() {
    }

    public Customer(Long entity_id) {
        this.entity_id = entity_id;
    }

    public Customer(Long entity_id, String firstname, String middlename, String lastname, String email, String dob, String facebook_id, Boolean is_login_fb, String picture_url, Integer cart_items_count, Integer wishlist_items_count, Integer unread_alerts_count, String shipping_address, String billing_address, Integer is_notification_sound, Integer orders_count, Integer reward_points, Double evoucher_amount, Integer log_num, String card_code) {
        this.entity_id = entity_id;
        this.firstname = firstname;
        this.middlename = middlename;
        this.lastname = lastname;
        this.email = email;
        this.dob = dob;
        this.facebook_id = facebook_id;
        this.is_login_fb = is_login_fb;
        this.picture_url = picture_url;
        this.cart_items_count = cart_items_count;
        this.wishlist_items_count = wishlist_items_count;
        this.unread_alerts_count = unread_alerts_count;
        this.shipping_address = shipping_address;
        this.billing_address = billing_address;
        this.is_notification_sound = is_notification_sound;
        this.orders_count = orders_count;
        this.reward_points = reward_points;
        this.evoucher_amount = evoucher_amount;
        this.log_num = log_num;
        this.card_code = card_code;
    }

    public Long getEntity_id() {
        return entity_id;
    }

    public void setEntity_id(Long entity_id) {
        this.entity_id = entity_id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getMiddlename() {
        return middlename;
    }

    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getFacebook_id() {
        return facebook_id;
    }

    public void setFacebook_id(String facebook_id) {
        this.facebook_id = facebook_id;
    }

    public Boolean getIs_login_fb() {
        return is_login_fb;
    }

    public void setIs_login_fb(Boolean is_login_fb) {
        this.is_login_fb = is_login_fb;
    }

    public String getPicture_url() {
        return picture_url;
    }

    public void setPicture_url(String picture_url) {
        this.picture_url = picture_url;
    }

    public Integer getCart_items_count() {
        return cart_items_count;
    }

    public void setCart_items_count(Integer cart_items_count) {
        this.cart_items_count = cart_items_count;
    }

    public Integer getWishlist_items_count() {
        return wishlist_items_count;
    }

    public void setWishlist_items_count(Integer wishlist_items_count) {
        this.wishlist_items_count = wishlist_items_count;
    }

    public Integer getUnread_alerts_count() {
        return unread_alerts_count;
    }

    public void setUnread_alerts_count(Integer unread_alerts_count) {
        this.unread_alerts_count = unread_alerts_count;
    }

    public String getShipping_address() {
        return shipping_address;
    }

    public void setShipping_address(String shipping_address) {
        this.shipping_address = shipping_address;
    }

    public String getBilling_address() {
        return billing_address;
    }

    public void setBilling_address(String billing_address) {
        this.billing_address = billing_address;
    }

    public Integer getIs_notification_sound() {
        return is_notification_sound;
    }

    public void setIs_notification_sound(Integer is_notification_sound) {
        this.is_notification_sound = is_notification_sound;
    }

    public Integer getOrders_count() {
        return orders_count;
    }

    public void setOrders_count(Integer orders_count) {
        this.orders_count = orders_count;
    }

    public Integer getReward_points() {
        return reward_points;
    }

    public void setReward_points(Integer reward_points) {
        this.reward_points = reward_points;
    }

    public Double getEvoucher_amount() {
        return evoucher_amount;
    }

    public void setEvoucher_amount(Double evoucher_amount) {
        this.evoucher_amount = evoucher_amount;
    }

    public Integer getLog_num() {
        return log_num;
    }

    public void setLog_num(Integer log_num) {
        this.log_num = log_num;
    }

    public String getCard_code() {
        return card_code;
    }

    public void setCard_code(String card_code) {
        this.card_code = card_code;
    }

}
