package greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import greendao.CategoryDao;
import greendao.BrandDao;
import greendao.CustomerDao;
import greendao.ProductDao;
import greendao.WishlistDao;
import greendao.CartDetailDao;
import greendao.CartItemDao;
import greendao.CountryDao;
import greendao.ConfigAttributeDao;
import greendao.ConfigOptionDao;
import greendao.ConfigProductDao;
import greendao.ConfigMergeDao;
import greendao.NotificationDao;
import greendao.AlertNotifiedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CategoryDao.createTable(db, ifNotExists);
        BrandDao.createTable(db, ifNotExists);
        CustomerDao.createTable(db, ifNotExists);
        ProductDao.createTable(db, ifNotExists);
        WishlistDao.createTable(db, ifNotExists);
        CartDetailDao.createTable(db, ifNotExists);
        CartItemDao.createTable(db, ifNotExists);
        CountryDao.createTable(db, ifNotExists);
        ConfigAttributeDao.createTable(db, ifNotExists);
        ConfigOptionDao.createTable(db, ifNotExists);
        ConfigProductDao.createTable(db, ifNotExists);
        ConfigMergeDao.createTable(db, ifNotExists);
        NotificationDao.createTable(db, ifNotExists);
        AlertNotifiedDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CategoryDao.dropTable(db, ifExists);
        BrandDao.dropTable(db, ifExists);
        CustomerDao.dropTable(db, ifExists);
        ProductDao.dropTable(db, ifExists);
        WishlistDao.dropTable(db, ifExists);
        CartDetailDao.dropTable(db, ifExists);
        CartItemDao.dropTable(db, ifExists);
        CountryDao.dropTable(db, ifExists);
        ConfigAttributeDao.dropTable(db, ifExists);
        ConfigOptionDao.dropTable(db, ifExists);
        ConfigProductDao.dropTable(db, ifExists);
        ConfigMergeDao.dropTable(db, ifExists);
        NotificationDao.dropTable(db, ifExists);
        AlertNotifiedDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(BrandDao.class);
        registerDaoClass(CustomerDao.class);
        registerDaoClass(ProductDao.class);
        registerDaoClass(WishlistDao.class);
        registerDaoClass(CartDetailDao.class);
        registerDaoClass(CartItemDao.class);
        registerDaoClass(CountryDao.class);
        registerDaoClass(ConfigAttributeDao.class);
        registerDaoClass(ConfigOptionDao.class);
        registerDaoClass(ConfigProductDao.class);
        registerDaoClass(ConfigMergeDao.class);
        registerDaoClass(NotificationDao.class);
        registerDaoClass(AlertNotifiedDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
