package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTIFICATION.
 */
public class Notification {

    private Long id;
    private Long account_id;
    private Long type_id;
    private String type;
    private String title;
    private String message;
    private Integer is_read;
    private Integer is_remove;
    private String created_at;
    private String updated_at;

    public Notification() {
    }

    public Notification(Long id) {
        this.id = id;
    }

    public Notification(Long id, Long account_id, Long type_id, String type, String title, String message, Integer is_read, Integer is_remove, String created_at, String updated_at) {
        this.id = id;
        this.account_id = account_id;
        this.type_id = type_id;
        this.type = type;
        this.title = title;
        this.message = message;
        this.is_read = is_read;
        this.is_remove = is_remove;
        this.created_at = created_at;
        this.updated_at = updated_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccount_id() {
        return account_id;
    }

    public void setAccount_id(Long account_id) {
        this.account_id = account_id;
    }

    public Long getType_id() {
        return type_id;
    }

    public void setType_id(Long type_id) {
        this.type_id = type_id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getIs_read() {
        return is_read;
    }

    public void setIs_read(Integer is_read) {
        this.is_read = is_read;
    }

    public Integer getIs_remove() {
        return is_remove;
    }

    public void setIs_remove(Integer is_remove) {
        this.is_remove = is_remove;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

}
