package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT.
 */
public class Product {

    private Long entity_id;
    private String type_id;
    private String name;
    private String sku;
    private String manufacturer;
    private String short_description;
    private Float price;
    private Float special_price;
    private String small_image_url;
    private String thumbnail_url;
    private String news_from_date;
    private String news_to_date;
    private String created_at;
    private String updated_at;
    private Integer is_product_new;
    private Integer is_product_sale;

    public Product() {
    }

    public Product(Long entity_id) {
        this.entity_id = entity_id;
    }

    public Product(Long entity_id, String type_id, String name, String sku, String manufacturer, String short_description, Float price, Float special_price, String small_image_url, String thumbnail_url, String news_from_date, String news_to_date, String created_at, String updated_at, Integer is_product_new, Integer is_product_sale) {
        this.entity_id = entity_id;
        this.type_id = type_id;
        this.name = name;
        this.sku = sku;
        this.manufacturer = manufacturer;
        this.short_description = short_description;
        this.price = price;
        this.special_price = special_price;
        this.small_image_url = small_image_url;
        this.thumbnail_url = thumbnail_url;
        this.news_from_date = news_from_date;
        this.news_to_date = news_to_date;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.is_product_new = is_product_new;
        this.is_product_sale = is_product_sale;
    }

    public Long getEntity_id() {
        return entity_id;
    }

    public void setEntity_id(Long entity_id) {
        this.entity_id = entity_id;
    }

    public String getType_id() {
        return type_id;
    }

    public void setType_id(String type_id) {
        this.type_id = type_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getShort_description() {
        return short_description;
    }

    public void setShort_description(String short_description) {
        this.short_description = short_description;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Float getSpecial_price() {
        return special_price;
    }

    public void setSpecial_price(Float special_price) {
        this.special_price = special_price;
    }

    public String getSmall_image_url() {
        return small_image_url;
    }

    public void setSmall_image_url(String small_image_url) {
        this.small_image_url = small_image_url;
    }

    public String getThumbnail_url() {
        return thumbnail_url;
    }

    public void setThumbnail_url(String thumbnail_url) {
        this.thumbnail_url = thumbnail_url;
    }

    public String getNews_from_date() {
        return news_from_date;
    }

    public void setNews_from_date(String news_from_date) {
        this.news_from_date = news_from_date;
    }

    public String getNews_to_date() {
        return news_to_date;
    }

    public void setNews_to_date(String news_to_date) {
        this.news_to_date = news_to_date;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public Integer getIs_product_new() {
        return is_product_new;
    }

    public void setIs_product_new(Integer is_product_new) {
        this.is_product_new = is_product_new;
    }

    public Integer getIs_product_sale() {
        return is_product_sale;
    }

    public void setIs_product_sale(Integer is_product_sale) {
        this.is_product_sale = is_product_sale;
    }

}
