package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WISHLIST.
 */
public class Wishlist {

    private Long wishlist_item_id;
    private Long product_id;
    private String name;
    private String sku;
    private String manufacturer;
    private Float price;
    private String image_url;
    private String added_at;
    private String type_id;

    public Wishlist() {
    }

    public Wishlist(Long wishlist_item_id) {
        this.wishlist_item_id = wishlist_item_id;
    }

    public Wishlist(Long wishlist_item_id, Long product_id, String name, String sku, String manufacturer, Float price, String image_url, String added_at, String type_id) {
        this.wishlist_item_id = wishlist_item_id;
        this.product_id = product_id;
        this.name = name;
        this.sku = sku;
        this.manufacturer = manufacturer;
        this.price = price;
        this.image_url = image_url;
        this.added_at = added_at;
        this.type_id = type_id;
    }

    public Long getWishlist_item_id() {
        return wishlist_item_id;
    }

    public void setWishlist_item_id(Long wishlist_item_id) {
        this.wishlist_item_id = wishlist_item_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getAdded_at() {
        return added_at;
    }

    public void setAdded_at(String added_at) {
        this.added_at = added_at;
    }

    public String getType_id() {
        return type_id;
    }

    public void setType_id(String type_id) {
        this.type_id = type_id;
    }

}
